In [130]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as mplot
import os
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler,RobustScaler,StandardScaler
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import make_pipeline

In [122]:
path = os.path.join(os.getcwd(),'data','housing.data')
print path
data = np.loadtxt(open(path),dtype=np.float32)

/home/sunny/Learnings/jupyter_notebooks/Housing_Price/data/housing.data


In [123]:
print data.shape
print data.dtype
print np.any(np.isnan(data))

(506, 14)
float32
False


In [124]:
data = np.random.permutation(data)
X,y = data[:,:13],data[:,-1]
print X.shape,y.shape

train_X,test_X,train_y,test_y = train_test_split(X,y,train_size=0.75)

print train_X.shape,test_X.shape,train_y.shape,test_y.shape

(506, 13) (506,)
(379, 13) (127, 13) (379,) (127,)


In [125]:
sc = StandardScaler()
sc.fit(train_X)
train_X_sc=sc.transform(train_X)
test_X_sc = sc.transform(test_X)

mmsc = MinMaxScaler()
mmsc.fit(train_X)
train_X_mmsc=mmsc.transform(train_X)
test_X_mmsc = mmsc.transform(test_X)

rsc = RobustScaler()
rsc.fit(train_X)
train_X_rsc=rsc.transform(train_X)
test_X_rsc = rsc.transform(test_X)

In [126]:
knr1 = KNeighborsRegressor(n_neighbors=3)
knr1.fit(train_X_sc,train_y)
print knr1.score(test_X_sc,test_y)

knr2 = KNeighborsRegressor(n_neighbors=3)
knr2.fit(train_X_mmsc,train_y)
print knr2.score(test_X_mmsc,test_y)

knr3 = KNeighborsRegressor(n_neighbors=3)
knr3.fit(train_X_rsc,train_y)
print knr3.score(test_X_rsc,test_y)

cross_val_score(KNeighborsRegressor(n_neighbors=3),X,y,cv=4)

0.763816062035
0.732241706262
0.824185190783


array([ 0.48886561,  0.5367893 ,  0.55244504,  0.45572218])

In [127]:
lr1 = LinearRegression()
lr1.fit(train_X_sc,train_y)
print lr1.score(test_X_sc,test_y)

lr2 = LinearRegression()
lr2.fit(train_X_mmsc,train_y)
print lr2.score(test_X_mmsc,test_y)

lr3 = LinearRegression()
lr3.fit(train_X_rsc,train_y)
print lr3.score(test_X_rsc,test_y)

cross_val_score(LinearRegression(),X,y,cv=5)

0.763957235888
0.76395752894
0.763957400294


array([ 0.75356023,  0.704107  ,  0.80128102,  0.70630149,  0.65038043])

In [128]:
lr1 = Lasso()
lr1.fit(train_X_sc,train_y)
print lr1.score(test_X_sc,test_y)

lr2 = Lasso()
lr2.fit(train_X_mmsc,train_y)
print lr2.score(test_X_mmsc,test_y)

lr3 = Lasso()
lr3.fit(train_X_rsc,train_y)
print lr3.score(test_X_rsc,test_y)

cross_val_score(Lasso(),X,y,cv=4)

0.735461741616
0.305450437248
0.743840491872


array([ 0.63535873,  0.66161362,  0.69807311,  0.62693052])

In [129]:
lr1 = Ridge()
lr1.fit(train_X_sc,train_y)
print lr1.score(test_X_sc,test_y)

lr2 = Ridge()
lr2.fit(train_X_mmsc,train_y)
print lr2.score(test_X_mmsc,test_y)

lr3 = Ridge()
lr3.fit(train_X_rsc,train_y)
print lr3.score(test_X_rsc,test_y)

cross_val_score(Ridge(),X,y,cv=4)

0.765512454446
0.774564114384
0.768967434338


array([ 0.72193415,  0.77348788,  0.68780586,  0.66379797])